version: '3'

services:

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./persistent/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_EXPOSE_PORT}:5432"
    logging:
      driver: "none"

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT:-8080}:8080